const DIRECTION_UP = 'up';
const DIRECTION_RIGHT = 'right';
const DIRECTION_DOWN = 'down';
const DIRECTION_LEFT = 'left';

const AVAILABLE_DIRECTIONS = [
  DIRECTION_UP,
  DIRECTION_RIGHT,
  DIRECTION_DOWN,
  DIRECTION_LEFT
];

module.exports = {
  DIRECTION_UP: DIRECTION_UP,
  DIRECTION_RIGHT: DIRECTION_RIGHT,
  DIRECTION_DOWN: DIRECTION_DOWN,
  DIRECTION_LEFT: DIRECTION_LEFT,
  AVAILABLE_DIRECTIONS: AVAILABLE_DIRECTIONS
};